declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.webp";
declare module "crypto-js";
declare module "notifyjs";
declare module "sweetalert2";
declare module "bcryptjs";
